version: "3"
services:
  book_service:
    hostname: book-service
    container_name: book-service
    build:
      context: .
    ports:
      - "50051:50051"
    networks:
      - default
      
networks:
  default:
    external:
      name: books